# Site settings

url: "https://fmartinelli.github.io"
baseurl: ""
google-tracking-id: ""
force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Fernan Martinelli"
title: "{ Fernan Martinelli }"
description: "Website of Fernan Martinelli. Feel free to Share."
keywords: "martinelli, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
  - text: "The master has failed more times than the beginner has ever tried"
  - text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand."

me-img: "/img/profile.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########
enable-gesture-navigation: True
post-preview-words: 96
paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "fmartinelli"
syntax-highlight: True

############
# Timeline #
############
events:
  - image: "/img/timeline/toptive.png"
    date: "August 2018 - Present"
    description: "Technical Leader @ <a href=\"https://www.toptive.co\" target=\"_blank\">Toptive SA.</a>"
  - image: "/img/timeline/onapsis.png"
    date: "Mar 2018 - August 2018"
    description: "Remote Python Developer @ <a href=\"https://www.onapsis.com/\" target=\"_blank\">Onapsis SRL. </a>"
  - image: "/img/timeline/ascentio.png"
    date: "Apr 2015 - Feb 2018"
    description: "Python and C++ Developer @ <a href=\"https://www.ascentio.com.ar/en/home/\" target=\"_blank\">Ascentio Technologies SA. </a>"
  - image: "/img/timeline/vates.png"
    date: "Oct 2014 - Apr 2015"
    description: "I have worked for <a href=\"http://www.arris.com/\" target=\"_blank\">Arris</a> as a member of WHS Core Team (Contractor from <a href=\"http://www.vates.com/\" target=\"_blank\">Vates SA</a>)."
  - image: "/img/timeline/freelancer.png"
    date: "Nov 2014 - Today"
    description: "I have been working as a freelancer in some startups and small projects."
  - image: "/img/timeline/taller.png"
    date: "Jun 2013 - May 2014"
    description: "C++ Software Engineer @ <a href=\"http://www.tallertechnologies.com\" target=\"_blank\">Taller Technologies</a>. I was member of Special Projects Division (SPD)."
  - image: "/img/timeline/fudepan.png"
    date: "Feb 2012 - Dec 2105"
    description: "I did my <a href=\"https://bitbucket.org/fudepan/r-emo\" target=\"_blank\">thesis</a> in Bioinformatics and I was a C++ collaborator on <a href=\"https://bitbucket.org/account/user/fudepan/projects/PROJ\" target=\"_blank\">FuDePAN</a>."
  - image: "/img/timeline/unrc.png"
    date: "Feb 2009 - Mar 2013"
    description: "Bachelor studies @ <a href=\"https://www.unrc.edu.ar/\" target=\"_blank\">Universidad Nacional de Rio Cuarto</a> on Computer Science. Teaching Assistant (non tenured)."

# First image of the Timeline
timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "fmartinelli89@gmail.com"

################
# Author Blurb #
################
# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.
# if the author_blurb is not set, then this feature is skipped
author_blurb: "Fernan Martinelli ..."
author_blurb_image: "/img/profile.jpg"

##################
# Social Buttons #
##################
social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/fernan-martinelli/"
  - title: "github"
    url: "https://github.com/fmartinelli"

############
# 404 page #
############
err-404-img: "/img/labtocat.png"

################################################################################
# NB! Tread carefully if you want to change the variables below this point!
# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site
exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path
paginate_path: "blog/page:num/"

# Enable minification SASS
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
